### ISSUE TITLE
README.md 오타

### ISSUE THREAD

**Issue by niceb5y** [ynifamily3/2017#4]
**Birtyday**가 뭐죠

**Comment by niceb5y** [comment]
컴퓨터가 없어서 풀리퀘를 못해주겠다.

**Comment by ynifamily3** [comment]
수정 완료 ㅇㅅㅇ

**Comment by vbalien** [comment]
https://github.com/ynifamily3/2017/blame/gh-pages/README.md#L4

수정 안됨

**Comment by ynifamily3** [comment]
다시 수정해씀
