### ISSUE TITLE
Publish issue

### ISSUE THREAD

**Issue by vbalien** [ynifamily3/2017#8]
`index.html`랑 다른 리소스들도 `dist/` 에 옮기고 publish할때 `dist/*`를 `gh-pages` 브랜치에 푸시하는게 어떰?

https://github.com/tschaub/gh-pages

이런거 써도 좋고

**Comment by ynifamily3** [comment]
main은 source고 gh-pages는  프로덕션용이라고 보면 되남 ㅇㅅㅇ

**Comment by vbalien** [comment]
master를 소스, gh-pages를 프로덕션으로

**Comment by niceb5y** [comment]
`/src` 디렉토리 만들고 `/docs`디렉토리에 빌드 시키면?
관리는 전부 `master`에서 하고...
https://github.com/blog/2228-simpler-github-pages-publishing
